<!DOCTYPE html>
<!-- <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us"> -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru"> 
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <title></title>
   <meta name="author" content="Tom Preston-Werner" />
   <link href="http://feeds.feedburner.com/tom-preston-werner" rel="alternate" title="Tom Preston-Werner" type="application/atom+xml" />
   <link rel="shortcut icon" href="/favicon.ico" />


   <!-- syntax highlighting CSS -->
   <link rel="stylesheet" href="/css/syntax.css" type="text/css" />

   <!-- Homepage CSS -->
   <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" />

   <!-- Typekit -->
   <!--<script type="text/javascript" src="http://use.typekit.com/jpd0pfm.js"></script>
   <script type="text/javascript">try{Typekit.load();}catch(e){}</script>-->
</head>
<body>

<!-- ClickTale Top part -->
<script type="text/javascript">
  var WRInitTime=(new Date()).getTime();
</script>
<!-- ClickTale end of Top part -->

<div class="site">
  <h1 class="header"><a href="/"></a></h1>
  <div id="aa_motto_parent_div">      
    <div id="aa_motto_img_div">  
      <a href="/"><img id="aa_motto_img" src="/images/aa-logo-en.gif"
          alt="" />
      </a>    
    </div>    
    <div id="aa_motto_child_div" >
      <p>
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        ♦ 
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        <br />
         <br />
        <a href="mailto:"></a>        
      </p>
    </div>
  </div>

  <div class="title" id="aa_menu_div">
    <!--<a href="/">Анонимные Алкоголики</a>-->
    <a class="extra" href="/"></a>
    <a class="extra" href="/solution"></a>
    <a class="extra" href="/community"></a>
    <a class="extra" href="/stories"></a>
    <a class="extra" href="/links"></a>
  </div>

 
<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/news/2011/01/16/id-00005.html">I've just written a helper new_post.rb</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00004.html">Молитва Нашей Шаговой Группы</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/news/2011/01/16/id-00003.html">Switching to Rails. This an Example of a Post. (markdown)</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00002.html">Switching to Rails. This an Example of a Post. (markdown)</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00001.html">Switching to Rails. This an Example of a Post. (textile)</a></h2>
</article>

<article class="post">
    <!--<time>18 Apr 2010</time>-->
    <h2><a rel="bookmark" href="/solution/2010/04/18/ironruby-drops-make-some-noise.html">IronRuby drops - make some noise!</a></h2>
</article>

<article class="post">
    <!--<time>03 Feb 2010</time>-->
    <h2><a rel="bookmark" href="/solution/2010/02/03/the-rails-module.html">The Rails Module (in Rails 3)</a></h2>
</article>

<article class="post">
    <!--<time>10 Nov 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/11/10/load-rails-conditionally-with-rack.html">Load Rails conditionally with Rack</a></h2>
</article>

<article class="post">
    <!--<time>14 Oct 2009</time>-->
    <h2><a rel="bookmark" href="/2009/10/14/gem-bundler-is-the-future.html">Gem Bundler is the Future</a></h2>
</article>

<article class="post">
    <!--<time>09 Oct 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/10/09/on-gem-forking.html">On Gem Forking</a></h2>
</article>

<article class="post">
    <!--<time>20 Jul 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/07/20/railscamp-ne-adventures.html">RailsCamp NE Adventures</a></h2>
</article>

<article class="post">
    <!--<time>19 May 2009</time>-->
    <h2><a rel="bookmark" href="/news/2009/05/19/the-git-parable.html">The Git Parable</a></h2>
</article>

<article class="post">
    <!--<time>26 Apr 2009</time>-->
    <h2><a rel="bookmark" href="/news/2009/04/26/barcamp-boston-4-roundup.html">BarCamp Boston 4 Roundup</a></h2>
</article>

<article class="post">
    <!--<time>11 Dec 2008</time>-->
    <h2><a rel="bookmark" href="/news/2008/12/11/if-you-only-could-follow-10-people-on-twitter.html">If you only could follow 10 people on Twitter...</a></h2>
</article>

<article class="post">
    <!--<time>26 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/news/2008/10/26/github-rebase-1.html">GitHub Rebase qqqq qqqqqqqqqqqqq qqqqqqqqqqq qqqqqqq qqqqqqq qqqqqqqqqq qqqqq qq qqqqqqqqqq qqqqq</a></h2>
</article>

<article class="post">
    <!--<time>20 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/news/2008/10/20/pumpkin-carving-2008.html">Pumpkin Carving 2008</a></h2>
</article>

<article class="post">
    <!--<time>19 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/10/19/where-do-you-get-ruby-news-from.html">Where do you get Ruby news from?</a></h2>
</article>

<article class="post">
    <!--<time>13 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/10/13/calculating-age-in-rails.html">Calculating Age in Rails</a></h2>
</article>

<article class="post">
    <!--<time>22 Sep 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/09/22/loading-custom-code-in-rails.html">Loading custom code in Rails</a></h2>
</article>

<article class="post">
    <!--<time>18 Sep 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/09/18/switching-to-rails.html">Switching to Rails</a></h2>
</article>

<article class="post">
    <!--<time>25 Mar 2008</time>-->
    <h2><a rel="bookmark" href="/news/2008/03/25/why-i-love-twitter.html">Why I love Twitter</a></h2>
</article>

<article class="post">
    <!--<time>16 Mar 2008</time>-->
    <h2><a rel="bookmark" href="/news/2008/03/16/turning-off-the-firehose.html">Turning off the Firehose</a></h2>
</article>

<article class="post">
    <!--<time>31 Oct 2007</time>-->
    <h2><a rel="bookmark" href="/news/2007/10/31/digg-labs-flash-doesnt-suck-all-the-time.html">Digg Labs: Flash doesn&#8217;t suck all the time.</a></h2>
</article>

<article class="post">
    <!--<time>11 Aug 2007</time>-->
    <h2><a rel="bookmark" href="/stories/2007/08/11/getting-baselined.html">Getting baselined</a></h2>
</article>

<article class="post">
    <!--<time>16 Aug 2006</time>-->
    <h2><a rel="bookmark" href="/links/2006/08/16/accessibility-and-why-should-i-care.html">Accessibility and why should I care</a></h2>
</article>

<article class="post">
    <!--<time>10 Aug 2006</time>-->
    <h2><a rel="bookmark" href="/community/2006/08/10/the-web-development-process.html">The Web Development Process</a></h2>
</article>


  
  <div class="footer">
    <div class="contact">
      <p>
        <br />
        <br />
        <a href="mailto:"></a>        
      </p>
    </div>
    <!--<div class="contact">
      <p>
        +79601979248<br />
        <a href="http://twitter.com/mojombo/">twitter.com/mojombo</a><br />
        <a href="http://flickr.com/photos/mojombo/">flickr.com/photos/mojombo</a>
      </p>
    </div>-->
    <div class="rss">
      <a href="http://feeds.feedburner.com/tom-preston-werner">
        <img src="/images/rss.png" alt="Subscribe to RSS Feed" />
      </a>
    </div>
  </div>
</div>

<!--<a href="http://github.com/mojombo"><img style="position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub" /></a>-->

<!-- ClickTale Bottom part -->
<!--<div id="ClickTaleDiv" style="display: none;"></div>
<script type="text/javascript">
if(document.location.protocol!='https:')
  document.write(unescape("%3Cscript%20src='http://s.clicktale.net/WRb.js'%20type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
if(typeof ClickTale=='function') ClickTale(206,0.3,"www03");
</script>-->
<!-- ClickTale end of Bottom part -->

<!-- Google Analytics -->
<!--<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-6016902-1");
pageTracker._trackPageview();
</script>-->
<!-- Google Analytics end -->

</body>
</html>
<!-- vim: set sts=2 sw=2 et: --> 
