<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru"> 
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <title>Анонимные Алкоголики Нижний Новгород</title>
   <meta name="author" content="Анонимные Алкоголики Нижний Новгород" />
   <meta name="description"
         content="Алкоголизм - выход есть! Анонимные Алкоголики Нижний Новгород. Адреса групп, контактные телефоны, новости и статьи." />
   <meta name="keywords" content="алкоголизм, нижний новгород, анонимные алкоголики, адреса групп аа, адреса собраний аа, aa, аа, 12 шагов, сообщество аа, содружество аа" /> 
   <link href="http://feeds.feedburner.com/aannovru" rel="alternate" 
         title="Анонимные Алкоголики Нижний Новгород" type="application/atom+xml" />
   <link rel="shortcut icon" href="/favicon.ico" />

   <!-- syntax highlighting CSS -->
   <link rel="stylesheet" href="/css/syntax.css" type="text/css" />

   <!-- Homepage CSS -->
   <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" />
</head>
<body>

<div class="site">
  <h1 class="header"><a href="/"></a></h1>
  <div id="aa_motto_parent_div">      
    <div id="aa_motto_img_div">  
      <a href="/"><img id="aa_motto_img" src="/images/aa-logo-en.gif"
          alt="" />
      </a>    
    </div>    

    <div id="aa_motto_child_div" >
      <p>
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        ♦ 
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        <br />
         <br />
        <a href="mailto:"></a>        
      </p>
    </div>
  </div>

  <div class="title" id="aa_menu_div">
    <a class="extra" href="/"></a>
    <a class="extra" href="/solution"></a>
    <a class="extra" href="/community"></a>
    <a class="extra" href="/stories"></a>
    <a class="extra" href="/links"></a>
  </div>

 
<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00009.html">Что такое Анонимные Алкоголики (АА)?</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00008.html">Молитва о Душевном Покое</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00007.html">Молитва 3-ого Шага</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/groups.html">Адреса групп в Нижнем Новгороде и области</a></h2>
</article>

<article class="post">
    <!--<time>17 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/news/2011/01/17/id-00006.html">Зарегистрированы домены для сайта Анонимных Алкоголиков Нижнего Новгорода</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00004.html">Молитва Нашей Шаговой Группы</a></h2>
</article>


  
  <div class="footer">
    <div class="contact">
      <p>
        <br />
        <br />
        <a href="mailto:"></a>        
      </p>
    </div>

    <div class="rss">
      <a href="http://feeds.feedburner.com/aannovru">
        <img src="/images/rss.png" alt="Subscribe to RSS Feed" />
      </a>
    </div>
  </div>
</div>

</body>
</html>
<!-- vim: set sts=2 sw=2 et: --> 
