<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru"> 
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <title>Анонимные Алкоголики Нижний Новгород</title>
   <meta name="author" content="Анонимные Алкоголики Нижний Новгород" />
   <meta name="description"
         content="Алкоголизм - выход есть! Анонимные Алкоголики Нижний Новгород. Адреса групп, контактные телефоны, новости и статьи." />
   <meta name="keywords" content="алкоголизм, нижний новгород, анонимные алкоголики, адреса групп аа, адреса собраний аа, aa, аа, 12 шагов, сообщество аа, содружество аа" /> 
   <link href="http://feeds.feedburner.com/aannovru" rel="alternate" 
         title="Анонимные Алкоголики Нижний Новгород" type="application/atom+xml" />
   <link rel="shortcut icon" href="/favicon.ico" />

   <!-- syntax highlighting CSS -->
   <link rel="stylesheet" href="/css/syntax.css" type="text/css" />

   <!-- Homepage CSS -->
   <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" />
</head>
<body>

<div class="site">
  <h1 class="header"><a href="/"></a></h1>
  <div id="aa_motto_parent_div">      
    <div id="aa_motto_img_div">  
      <a href="/"><img id="aa_motto_img" src="/images/aa-logo-en.gif"
          alt="" />
      </a>    
    </div>    

    <div id="aa_motto_child_div" >
      <p>
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        ♦ 
        <a id="aa_motto_link_no_underline" class="aa_motto_link_no_underline" href="/solution">    
          
        </a>
        <br />
         <br />
        <a href="mailto:"></a>        
      </p>
    </div>
  </div>

  <div class="title" id="aa_menu_div">
    <a class="extra" href="/"></a>
    <a class="extra" href="/solution"></a>
    <a class="extra" href="/community"></a>
    <a class="extra" href="/stories"></a>
    <a class="extra" href="/links"></a>
  </div>

 
<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00009.html">Что такое Анонимные Алкоголики (АА)?</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00008.html">Молитва о Душевном Покое</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/18/id-00007.html">Молитва 3-ого Шага</a></h2>
</article>

<article class="post">
    <!--<time>18 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/groups.html">Адреса групп в Нижнем Новгороде и области</a></h2>
</article>

<article class="post">
    <!--<time>17 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/news/2011/01/17/id-00006.html">Зарегистрированы домены для сайта Анонимных Алкоголиков Нижнего Новгорода</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00004.html">Молитва Нашей Шаговой Группы</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00002.html">Switching to Rails. This an Example of a Post. (markdown)</a></h2>
</article>

<article class="post">
    <!--<time>16 Jan 2011</time>-->
    <h2><a rel="bookmark" href="/solution/2011/01/16/id-00001.html">Switching to Rails. This an Example of a Post. (textile)</a></h2>
</article>

<article class="post">
    <!--<time>18 Apr 2010</time>-->
    <h2><a rel="bookmark" href="/solution/2010/04/18/ironruby-drops-make-some-noise.html">IronRuby drops - make some noise!</a></h2>
</article>

<article class="post">
    <!--<time>03 Feb 2010</time>-->
    <h2><a rel="bookmark" href="/solution/2010/02/03/the-rails-module.html">The Rails Module (in Rails 3)</a></h2>
</article>

<article class="post">
    <!--<time>10 Nov 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/11/10/load-rails-conditionally-with-rack.html">Load Rails conditionally with Rack</a></h2>
</article>

<article class="post">
    <!--<time>09 Oct 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/10/09/on-gem-forking.html">On Gem Forking</a></h2>
</article>

<article class="post">
    <!--<time>20 Jul 2009</time>-->
    <h2><a rel="bookmark" href="/solution/2009/07/20/railscamp-ne-adventures.html">RailsCamp NE Adventures</a></h2>
</article>

<article class="post">
    <!--<time>19 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/10/19/where-do-you-get-ruby-news-from.html">Where do you get Ruby news from?</a></h2>
</article>

<article class="post">
    <!--<time>13 Oct 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/10/13/calculating-age-in-rails.html">Calculating Age in Rails</a></h2>
</article>

<article class="post">
    <!--<time>22 Sep 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/09/22/loading-custom-code-in-rails.html">Loading custom code in Rails</a></h2>
</article>

<article class="post">
    <!--<time>18 Sep 2008</time>-->
    <h2><a rel="bookmark" href="/solution/2008/09/18/switching-to-rails.html">Switching to Rails</a></h2>
</article>

<article class="post">
    <!--<time>11 Aug 2007</time>-->
    <h2><a rel="bookmark" href="/stories/2007/08/11/getting-baselined.html">Getting baselined</a></h2>
</article>

<article class="post">
    <!--<time>16 Aug 2006</time>-->
    <h2><a rel="bookmark" href="/links/2006/08/16/accessibility-and-why-should-i-care.html">Accessibility and why should I care</a></h2>
</article>

<article class="post">
    <!--<time>10 Aug 2006</time>-->
    <h2><a rel="bookmark" href="/community/2006/08/10/the-web-development-process.html">The Web Development Process</a></h2>
</article>


  
  <div class="footer">
    <div class="contact">
      <p>
        <br />
        <br />
        <a href="mailto:"></a>        
      </p>
    </div>

    <div class="rss">
      <a href="http://feeds.feedburner.com/aannovru">
        <img src="/images/rss.png" alt="Subscribe to RSS Feed" />
      </a>
    </div>
  </div>
</div>

</body>
</html>
<!-- vim: set sts=2 sw=2 et: --> 
